### ISSUE TITLE
Should warn the Plugin name with ==?

### ISSUE THREAD

**Issue by davidperezgar** [afragen/wordpress-plugin-readme-parser#12]
Hello, 
While we review plugins, We warn developers to use === Plugin Name === as a correct convention instead ==. 

Is it really true? or is correct to use as well == Plugin Name == ? 

Thanks

**Comment by afragen** [comment]
You should really ask this in the #pluginreview channel in WordPress Slack. I simply maintain a copy of the parser for use in plugins.
