### ISSUE TITLE
Return raw values from the Parser

### ISSUE THREAD

**Issue by ernilambar** [afragen/wordpress-plugin-readme-parser#2]
Ref: https://github.com/WordPress/plugin-check/issues/198

We have been using this package in `Plugin Check`. During expansion of readme check in the plugin, we needed some raw data rather than calculated after fallback.
Example:
* We need actual short description. (Currently short description is trimmed to 150 characters and it is also calculated with fallback to description and like that.
* We need actual tags in the readme file to warn if there are more than 5 tags. (Currently those are sliced down to 5 tags from the parser itself)

We could create separate variables like `short_description_raw` and `tags_raw` or any other suitable names.

**Comment by ernilambar** [comment]
Closing ticket. Not appropriate place for the issue.

**Comment by afragen** [comment]
I think you will need to open a #meta Trac ticket and ping @dd32
